---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: prototype-pvc-
  namespace: tekton-devfile-prototype
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
