---
apiVersion: v1
kind: Secret
metadata:
  name: my-docker-creds
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
#  username: FILL IN YOUR INFO!
#  password: FILL IN YOUR INFO!
