apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: change-manifest
spec:
  workspaces:
    - name: source
      mountPath: /source
  steps:
    # Adam's big note - this isn't scalable as one may have a deployment/manifest spec with 
    # multiple image: references, and this would replace them all. So todo sure up that being fine or 
    # do in a more robust way.
    - name: change-manifest
      image: mikefarah/yq
      script: |
        echo "todo change manifest, it's: $(cat /source/manifest.yaml)"
