apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: path # Can be a file or directory
  steps:
    - name: deploy
      image: lachlanevenson/k8s-kubectl
      script: |
        echo "todo, thing to deploy: /source/$(params.path)"