apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: manifestSubPath
      default: manifest.yaml
  steps:
    - name: deploy
      image: lachlanevenson/k8s-kubectl
      script: |
        echo "$(workspaces.source.path)/$(params.manifestSubPath)"
        cat "$(workspaces.source.path)/$(params.manifestSubPath)"
        kubectl apply -f "$(workspaces.source.path)/$(params.manifestSubPath)"
