apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prototype-pvc-claim
  namespace: tekton-devfile-prototype
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
