apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-dockerfile
spec:
  workspaces:
    - name: source
      mountPath: /source
  params: 
    - name: devfilePath
      default: "repo/devfile.yaml"
    - name: dockerfilePath
      default: "Dockerfile"
  steps:
    - name: fetch-dockerfile
      image: mikefarah/yq
      script: |
        DEVFILE="$(workspaces.source.path)/$(params.devfilePath)"
        LOOKUP='components.(id==build-image).dockerfile.path'
        DOCKERFILE_URL=$(yq r $DEVFILE $LOOKUP) 
        wget -O "$(workspaces.source.path)/$(params.dockerfilePath)" $DOCKERFILE_URL
