apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-and-fill-manifest
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: devfilePath
      default: repo/devfile.yaml
    - name: manifestSubPath
      default: manifest.yaml
    - name: newImage
      type: string
  steps:
    - name: fetch-manifest
      image: mikefarah/yq
      script: |
        MANIFEST_PATH="$(workspaces.source.path)/$(params.manifestSubPath)"
        DEVFILE="$(workspaces.source.path)/$(params.devfilePath)"
        LOOKUP='components.(id==deploy-image).manifest.path'
        cat $DEVFILE
        echo $LOOKUP
        echo "done the lookup"
        MANIFEST_URL=$(yq r $DEVFILE $LOOKUP)
        wget -O $MANIFEST_PATH $MANIFEST_URL
        yq w -i $MANIFEST_PATH 'spec.applicationImage' "$(params.newImage)"
        echo "Manifest at $(MANIFEST_PATH), printing it"
        cat $MANIFEST_PATH
