---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prototype
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: subdirectory
          value: repo
    - name: fetch-dockerfile
      taskRef:
        name: fetch-dockerfile
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        name: buildah
      runAfter:
        - fetch-dockerfile
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: '$(params.image):$(tasks.fetch-repository.results.commit)'
        - name: CONTEXT
          value: repo/
    - name: fetch-and-fill-manifest
      taskRef:
        name: fetch-and-fill-manifest
      runAfter:
        - build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: newImage
          value: '$(params.image):$(tasks.fetch-repository.results.commit)'
    - name: deploy-app
      taskRef:
        name: deploy
      runAfter:
        - fetch-and-fill-manifest
      workspaces:
        - name: source
          workspace: shared-workspace
