apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prototype
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
  workspaces:
    - name: shared-workspace

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: subdirectory
          value: repo

    - name: fetch-dockerfile
      taskRef:
        name: fetch-dockerfile
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-and-push
      taskRef:
        name: buildah
      runAfter:
        - fetch-dockerfile
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.image)"
        - name: CONTEXT
          value: "repo/"

    - name: fetch-manifest
      taskRef:
        name: fetch-manifest
      runAfter:
        - build-and-push # Todo optimise: should we do this upfront instead of after build/push? Could be expensive
      workspaces:
        - name: source
          workspace: shared-workspace

      # This needs to replace metadata.name (at the top-level)
      # and spec.applicationImage, with what we've just built
    - name: change-manifest
      taskRef:
        name: change-manifest
      runAfter:
        - fetch-manifest
      workspaces:
        - name: source
          workspace: shared-workspace      

    - name: deploy-app
      taskRef:
        name: deploy
      runAfter:
        - change-manifest
      workspaces:
        - name: source
          workspace: shared-workspace
