---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devfile-role-binding
  namespace: tekton-devfile-prototype
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: tekton-devfile-prototype
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devfile-role
