---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devfile-role
rules:
  - apiGroups:
      - app.stacks
    resources:
      - runtimecomponents
    verbs:
      - get
      - create
      - update
      - watch
      - list
      - patch
